### ISSUE TITLE
Support for laravel 7

### ISSUE THREAD

**Issue by duxthefux** [juhasev/LaravelCdn#3]
Hey,

I just noticed that `master` already supports laravel 7 but there is no release yet for it.

I also saw that these
```
"symfony/finder": "2.*|3.*|4.*",
"symfony/console": "2.*|3.*|4.*",
```

need to be adjusted to
```
"symfony/finder": "2.*|3.*|4.*|5.*",
"symfony/console": "2.*|3.*|4.*|5.*",
```
.

Let me know if I should prepare a pull request.
Thanks

**Comment by juhasev** [comment]
Go ahead and make a PR. We have not yet switched to Laravel 7 thus no updates to that yet.

**Comment by juhasev** [comment]
Laravel 7 has been added some time ago so closing this issue.
